# http://documentcloud.github.com/jammit/
package_assets:         on          # (on, off, always)
embed_assets:           off         # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
package_path:           bundles     # (defaults to assets)
javascript_compressor:  yui         # (yui, closure)

javascripts:
  all:
    - public/javascripts/jquery.js
#    - public/javascripts/jquery-ui.js # aparentemente não usado
    - public/javascripts/jrails.js
    - public/javascripts/application.js

stylesheets:
  all:
    - public/stylesheets/reset.css
    - public/stylesheets/application.css
